global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'board-service'
    metrics_path: /actuator/prometheus

    ec2_sd_configs:
      - region: ap-northeast-2
        port: 8080

    relabel_configs:
      - source_labels: [__meta_ec2_tag_Name]
        regex: board-service
        action: keep